### ISSUE TITLE
Reintegrate with ros/rosdistro repo

### ISSUE THREAD

**Issue by dirk-thomas** [ros2/rosdistro-testing#492]
For the initial development of ROS 2 we created this repo in order to keep it separate from `ros/rosdistro`. This enabled us to iterate quickly on standard / format changes.

Since that phase a lot of the involved pieces have stabilized and also aligned with ROS 1. E.g. both use the current version of `catkin_pkg` rather than a separate implementation for ROS 2.

Therefore it is time to reintegrate the two repos. The proposed steps for this are:

* [x] PR #493 to ros2/rosdistro to update the README mentioning the re-integration.
  * [x] Archive the repo afterwards.
* [x] PR ros2/ros2_documentation#91 to the docs to remove the need for a custom environment variable.
* [x] PR ros/rosdistro#19908 to integrate the ros2 content including its history. I would propose to only port the non-beta distros Ardent, Bouncy and Crystal though.
* [x] PR ros2/ros_buildfarm_config#15 to update the ROS 2 buildfarm config to point to the ros/rosdistro repo.
* [x] Reconfigure the ROS 2 buildfarm (to clarify: the ROS 2 buildfarm will still stay separate on build.ros2.org).
* [x] New bloom release to include ros-infrastructure/bloom#501: 0.7.0
* [x] Post announcement on discourse. [advisory announcement](https://discourse.ros.org/t/reintegrating-ros2-rosdistro-into-ros-rosdistro/7409).

**Comment by nuclearsandwich** [comment]
>     * I would propose to only port the non-beta distros Ardent, Bouncy and Crystal though.

Agreed.

**Comment by dirk-thomas** [comment]
I posted an announcement on discourse to let people know of the transition: https://discourse.ros.org/t/reintegrating-ros2-rosdistro-into-ros-rosdistro/7409

**Comment by nuclearsandwich** [comment]
bloom 0.7.0 is released with ros-infrastructure/bloom#501
